# Generated by Django 5.2.7 on 2025-11-24 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_p', models.CharField(max_length=20)),
                ('apellido_m', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=20)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('cod_post', models.IntegerField(blank=True, null=True)),
                ('estudios', models.CharField(max_length=50)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('ult_area_ocup', models.IntegerField(blank=True, null=True)),
                ('ult_exp', models.TextField(blank=True, null=True)),
                ('hard_skills', models.TextField(blank=True, null=True)),
                ('soft_skills', models.TextField(blank=True, null=True)),
                ('area_interes', models.IntegerField(blank=True, null=True)),
                ('intereses', models.TextField(blank=True, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
