# Generated by Django 5.2.7 on 2025-11-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0002_alter_trabajador_ult_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='descripcion_exp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
