# Generated by Django 5.2.7 on 2025-11-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0003_trabajador_biografia_trabajador_descripcion_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='movilidad_limitada',
            field=models.BooleanField(default=False),
        ),
    ]
