# Generated by Django 5.2.7 on 2025-12-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0004_trabajador_movilidad_limitada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='apellido_m',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='apellido_p',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='cod_post',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='telefono',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='_apellido_m_encriptado',
            field=models.CharField(db_column='apellido_m', default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='_apellido_p_encriptado',
            field=models.CharField(db_column='apellido_p', default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='_biografia_encriptada',
            field=models.TextField(db_column='bio', default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='_cp_encriptado',
            field=models.CharField(db_column='codigo_postal', default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='_email_encriptado',
            field=models.CharField(db_column='email', default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='_nombre_encriptado',
            field=models.CharField(db_column='nombre', default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='_telefono_encriptado',
            field=models.CharField(db_column='telefono', default='', max_length=500),
            preserve_default=False,
        ),
    ]
