# Generated by Django 5.2.7 on 2025-11-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_biografia_empresa_email_empresa_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='categoria',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
