# Generated by Django 5.2.7 on 2025-11-24 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresa_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_puesto', models.CharField(max_length=100, unique=True)),
                ('area_ocupacion', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(default='Descripción del puesto.')),
                ('requisitos', models.TextField(default='Requisitos del puesto.')),
                ('prestaciones', models.TextField(default='Prestaciones del puesto.')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('ubicacion', models.CharField(max_length=200)),
                ('horario', models.CharField(max_length=100)),
                ('tipo_contrato', models.CharField(max_length=100)),
                ('etiquetas', models.TextField(blank=True, null=True)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
        ),
    ]
