# Generated by Django 5.2.7 on 2025-11-24 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_vacante'),
        ('trabajadores', '0002_alter_trabajador_ult_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='En revisión', max_length=50)),
                ('D_A_fit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('N_S_fit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('P_O_fit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('compatibilidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.trabajador')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.vacante')),
            ],
        ),
    ]
