# Generated by Django 5.2.7 on 2025-11-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_postulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='postulaciones_count',
            field=models.IntegerField(default=0),
        ),
    ]
