# Generated by Django 5.2.7 on 2025-11-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_vacante_activa_vacante_postulaciones_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='nombre_puesto',
            field=models.CharField(max_length=100),
        ),
    ]
