# Generated by Django 5.2.7 on 2025-11-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_alter_vacante_nombre_puesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='escolaridad_minima',
            field=models.CharField(default='22', max_length=100),
        ),
        migrations.AddField(
            model_name='vacante',
            name='tiempo_experiencia',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
